version: "3.9"

services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "80:8000"
    environment:
      # Add any environment variables your app needs
      - APP_ENV=production
    restart: unless-stopped
